// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kusgvqndnwqhhmygikci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1c2d2cW5kbndxaGhteWdpa2NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMjk5NzIsImV4cCI6MjA1ODgwNTk3Mn0.31o1bHN1Csjo1g86lEqwIe95JvNgWLBr8GIWbZBi670";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);